# Initialization zellij
eval "$(zellij setup --generate-auto-start zsh)"

#Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/user-home/.oh-my-zsh"

# krew path
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"
KUBE_PS1_SYMBOL_ENABLE="false"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  kubectl
  zsh-syntax-highlighting
  zsh-autosuggestions
  pj
  z
  fzf
  )

source $ZSH/oh-my-zsh.sh

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias kbx="kubectx"
alias kubectl="kubecolor"

source /home/home-user/.zsh-scripts/kube-ps1/kube-ps1.sh
PROMPT='$(kube_ps1)'$PROMPT

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export USE_GKE_GCLOUD_AUTH_PLUGIN=True

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/home-user/Imágenes/google-cloud-sdk/path.zsh.inc' ]; then . '/home/home-user/Imágenes/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/home-user/Imágenes/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/home-user/Imágenes/google-cloud-sdk/completion.zsh.inc'; fi

#github token
export GITHUB_ACCESS_TOKEN=
export COMPOSER_AUTH='{"github-oauth": {"github.com": ""}}'

# pj config
export PROJECT_PATHS=(~/git ~/git/krato/ ~/git/krato-net/ ~/git/peter/ ~/git/devops/ ~/git/plum/ ~/git/fluid-code/)

# install asdf
. "$HOME/.asdf/asdf.sh"
# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)

export GEMINI_API_KEY=
export INFRACOST_API_KEY=

# terraform cloud fluid
export TF_TOKEN_app_terraform_io=""

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/home-user/.lmstudio/bin"

. "$HOME/.atuin/bin/env"

# atuin config
eval "$(atuin init zsh --disable-up-arrow)"
